language: android

android:
  components:
    - build-tools-20.0.0
    - android-21
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - export TERM=dumb

script:
  - ./gradlew build
